channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.25.2
  - matplotlib=3.7.2
  - numpy=1.24.4
  - pandas=2.1.0
  - python=3.11.5
  - scikit-learn=1.3.0
  - scipy=1.11.2
  - seaborn=0.12.2
  - statsmodels=0.14.0
