channels:
  - conda-forge
dependencies:
  - arviz
  - corner
  - cython
  - emcee
  - ipykernel
  - jax
  - jupyterlab
  - jupyterlab_widgets
  - keras
  - librosa
  - matplotlib
  - networkx
  - numba
  - numpy
  - optax
  - palmerpenguins
  - pandas
  - pymc
  - python=3.13
  - scikit-learn
  - scikit-image
  - seaborn
  - sympy
  - ipywidgets
  - imageio
