name: DataSciPy
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - ipykernel=6.25.2
  - ipywidgets=8.1.1
  - jax=0.4.19
  - jaxlib=0.4.14
  - keras=2.13.1
  - matplotlib=3.8.2
  - numba=0.59.0
  - numpy=1.26.4
  - pandas=2.2.0
  - python=3.11.5
  - scikit-image=0.22.0
  - scikit-learn=1.4.0
  - scipy=1.12.0
  - seaborn=0.12.2
  - statsmodels=0.14.0
  - tensorflow=2.13.1
  - pip:
      - corner==2.2.2
      - emcee==3.1.4
